Add-login-and-registration-page
yanoyo/fleamarket_sample_39l pull request #4
Opened 2019-03-02 05:49 UTC by blackwatcher

**WHAT
最終課題のログイン、新規会員登録ページを作成する。

**WHY
ユーザがサービスの利用を開始できるようにするため。

2019-03-02 05:59 UTC, b-i-hide reviewed
コメントしました〜！
ちょっとコミットの単位が大きすぎるので、次回からもっとこまめにコミットすることを意識してみてください〜！

2019-03-02 05:59 UTC, b-i-hide commented on app/assets/stylesheets/application.scss
> +@import "modules/user";
改行しましょう〜！

2019-03-02 06:19 UTC, blackwatcher commented on app/assets/stylesheets/application.scss
> +@import "modules/user";
申し訳ありません。
コメントありがとうございます。
改行を入れました。

2019-03-02 06:22 UTC, yuki-uchida requested changes

2019-03-02 06:22 UTC, yuki-uchida commented on app/assets/stylesheets/modules/user.scss
> +.l-single-container {
https://qiita.com/Takuan_Oishii/items/0f0d2c5dc33a9b2d9cb1
こちらの記事に従って、アンバサンドを活用した省略形でCSSを記述してください

2019-03-03 02:33 UTC, blackwatcher commented on app/assets/stylesheets/modules/user.scss
> +.l-single-container {
修正を実施しました。
お手数ですが、再度ご確認お願いできますでしょうか。

2019-03-03 02:40 UTC, yuki-uchida requested changes

2019-03-03 02:40 UTC, yuki-uchida commented on app/assets/stylesheets/modules/user.scss
> +.l-single-head {
このl_single〜ってやつのCSS、階層構造が把握できてないのですが、色々な場所で使われるものですか？

下の方にあるbtn-redとかもそうですが。

BEMでは基本的に
親{
  子{
    孫{}
｝
}
と言った形になるため、CSSの全体構造もこのような形にしてください。

色々な場所で使うCSSの場合には、ファイルを分け、mixinで呼び出すようにしましょう

2019-03-03 02:40 UTC, yuki-uchida commented on app/views/devise/shared/_links.html.haml
> +- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
brは禁止です。marginやpaddingで形を整えるようにしましょう

2019-03-03 04:32 UTC, blackwatcher commented on app/assets/stylesheets/modules/user.scss
> +.l-single-head {
何度も申し訳ありません。
いただいたフィードバックをもとにファイルを修正しました。

2019-03-03 04:32 UTC, blackwatcher commented on app/views/devise/shared/_links.html.haml
> +- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
こちらdeviseのviewを自動作成した際にできたものなのですが、修正が必要でしょうか？
ご確認お願いいたします。

2019-03-03 04:35 UTC, ghost requested changes
ここにある全てのビューファイルを使用しますか？
現時点で使う予定がないビューファイルは削除しましょう。

2019-03-03 04:36 UTC, hiroki5123 commented
> 最終課題のログイン、新規会員登録ページを作成する。

こちらの画面のキャプチャをプルリクエストに添付してください。

2019-03-03 04:49 UTC, blackwatcher commented
ご指摘ありがとうございます。下記を行いました。
・ビューファイルの削除
・イメージの添付（ページ上部に追加）

2019-03-03 04:51 UTC, ghost approved these changes
LGTMです！

2019-03-03 07:19 UTC, merged