[WIP]メルカリTopページ新規作成
yanoyo/fleamarket_sample_39l pull request #7
Opened 2019-03-10 11:22 UTC by akametee

#WHAT
メルカリTopページ(ログイン後)のマークアップ作成

#WHY
必須画面の構築

2019-03-10 11:26 UTC, yuki-uchida requested changes
修正点は主にCSSのBEMでのクラス命名になります。
参考に。
https://qiita.com/Takuan_Oishii/items/0f0d2c5dc33a9b2d9cb1

2019-03-10 11:26 UTC, yuki-uchida commented on app/assets/stylesheets/modules/footer-app__banner.scss
> +        .app__banner-logo {
BEMにしたがって、app_banner-icon-logoのようにして省略形で記述してください。
CSS全体の見直しをお願いします

2019-03-10 11:26 UTC, yuki-uchida commented on app/views/shared/_sell_btn.html.haml
> +  %i.fa.fa-camera
fa_icon使いましょう

2019-03-14 13:29 UTC, akametee commented on app/assets/stylesheets/modules/footer-app__banner.scss
> +        .app__banner-logo {
全体的に見直ししました。

2019-03-14 13:29 UTC, akametee commented on app/views/shared/_sell_btn.html.haml
> +  %i.fa.fa-camera
fa_iconに修正しました。

2019-03-14 13:35 UTC, akametee commented
![screencapture-localhost-3000-2019-03-14-22_32_04](https://user-images.githubusercontent.com/45488446/54360936-4d313a80-46a9-11e9-99a9-262f1987d8e8.png)

キャプチャ画像を添付します。ご確認ください。

2019-03-15 02:00 UTC, hzak2xx approved these changes
LGTM

2019-03-15 02:16 UTC, akametee commented on config/routes.rb
> +#   root 'application#hello'
root pathをproducts#indexに変更しました。問題なければコメントアウト部分を削除できればと思います。

2019-03-15 03:47 UTC, merged

2019-03-15 16:39 UTC, yanoyo commented on config/routes.rb
> +#   root 'application#hello'
root 'application#hello' の部分は削除しました。