Add product listing page
yanoyo/fleamarket_sample_39l pull request #8
Opened 2019-03-11 09:25 UTC by blackwatcher

#WHAT
商品出品ページのマークアップ。

#WHY
メルカリユーザが利用する必須機能の画面構築。

2019-03-11 09:47 UTC, ghost requested changes

2019-03-11 09:47 UTC, hiroki5123 commented on app/views/products/new.html.haml
> +                %a.sell-single-container__btn-default.sell-single-container__btn-box__btn-gray もどる
一応link_toで仮置きしておきましょう

2019-03-11 09:47 UTC, hiroki5123 commented on app/views/products/new.html.haml
> +                    %a{href: "/jp/help_center/getting_started/counterfeit_goods/", target: "_blank"} 偽ブランドの販売
一応link_toで仮置きしておきましょう

2019-03-11 09:47 UTC, hiroki5123 commented on app/views/products/new.html.haml
> +                    %a{href: "/jp/help_center/getting_started/prohibited_conduct/", target: "_blank"} 行為
一応link_toで仮置きしておきましょう

2019-03-11 09:47 UTC, hiroki5123 commented on app/views/products/new.html.haml
> +                        %option{value: "2"} 青森県
active_hashは使わない感じですか？

2019-03-11 23:46 UTC, blackwatcher commented on app/views/products/new.html.haml
> +                        %option{value: "2"} 青森県
active_hashを使う形に修正しました。

2019-03-11 23:46 UTC, blackwatcher commented on app/views/products/new.html.haml
> +                    %a{href: "/jp/help_center/getting_started/prohibited_conduct/", target: "_blank"} 行為
link_toに修正しました。

2019-03-11 23:46 UTC, blackwatcher commented on app/views/products/new.html.haml
> +                    %a{href: "/jp/help_center/getting_started/counterfeit_goods/", target: "_blank"} 偽ブランドの販売
link_toに修正しました。

2019-03-11 23:46 UTC, blackwatcher commented on app/views/products/new.html.haml
> +                %a.sell-single-container__btn-default.sell-single-container__btn-box__btn-gray もどる
link_toに修正しました。

2019-03-12 02:08 UTC, hzak2xx approved these changes
LGTM

2019-03-12 11:38 UTC, merged